language: ruby
cache: bundler
branches:
  only:
  -  master
addons:
  ssh_known_hosts: git.wpengine.com
script:
- cd wp-content/themes/defense360
- compass compile
before_install:
- openssl aes-256-cbc -K $encrypted_06196c1cb5d9_key -iv $encrypted_06196c1cb5d9_iv
  -in d360_travis.enc -out /tmp/d360_travis -d
- gem install compass
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
- provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh && sh deploy.sh
  on:
    branch: master
